# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/koen/Documents/GitHub/BrowserC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/koen/Documents/GitHub/BrowserC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/koen/Documents/GitHub/BrowserC/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koen/Documents/GitHub/BrowserC/CMakeFiles /home/koen/Documents/GitHub/BrowserC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koen/Documents/GitHub/BrowserC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/koen/Documents/GitHub/BrowserC/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HTMLParser

# Build rule for target.
HTMLParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HTMLParser
.PHONY : HTMLParser

# fast build rule for target.
HTMLParser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTMLParser.dir/build.make CMakeFiles/HTMLParser.dir/build
.PHONY : HTMLParser/fast

#=============================================================================
# Target rules for targets named MyApp

# Build rule for target.
MyApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyApp
.PHONY : MyApp

# fast build rule for target.
MyApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/build
.PHONY : MyApp/fast

#=============================================================================
# Target rules for targets named d8

# Build rule for target.
d8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 d8
.PHONY : d8

# fast build rule for target.
d8/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/d8.dir/build.make extern/v8/CMakeFiles/d8.dir/build
.PHONY : d8/fast

#=============================================================================
# Target rules for targets named shell

# Build rule for target.
shell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shell
.PHONY : shell

# fast build rule for target.
shell/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/shell.dir/build.make extern/v8/CMakeFiles/shell.dir/build
.PHONY : shell/fast

#=============================================================================
# Target rules for targets named hello-world

# Build rule for target.
hello-world: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello-world
.PHONY : hello-world

# fast build rule for target.
hello-world/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/hello-world.dir/build.make extern/v8/CMakeFiles/hello-world.dir/build
.PHONY : hello-world/fast

#=============================================================================
# Target rules for targets named v8-i18n-support

# Build rule for target.
v8-i18n-support: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8-i18n-support
.PHONY : v8-i18n-support

# fast build rule for target.
v8-i18n-support/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8-i18n-support.dir/build.make extern/v8/CMakeFiles/v8-i18n-support.dir/build
.PHONY : v8-i18n-support/fast

#=============================================================================
# Target rules for targets named v8_base_without_compiler

# Build rule for target.
v8_base_without_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_base_without_compiler
.PHONY : v8_base_without_compiler

# fast build rule for target.
v8_base_without_compiler/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_base_without_compiler.dir/build.make extern/v8/CMakeFiles/v8_base_without_compiler.dir/build
.PHONY : v8_base_without_compiler/fast

#=============================================================================
# Target rules for targets named v8_compiler

# Build rule for target.
v8_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_compiler
.PHONY : v8_compiler

# fast build rule for target.
v8_compiler/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_compiler.dir/build.make extern/v8/CMakeFiles/v8_compiler.dir/build
.PHONY : v8_compiler/fast

#=============================================================================
# Target rules for targets named v8_initializers

# Build rule for target.
v8_initializers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_initializers
.PHONY : v8_initializers

# fast build rule for target.
v8_initializers/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_initializers.dir/build.make extern/v8/CMakeFiles/v8_initializers.dir/build
.PHONY : v8_initializers/fast

#=============================================================================
# Target rules for targets named v8_snapshot

# Build rule for target.
v8_snapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_snapshot
.PHONY : v8_snapshot

# fast build rule for target.
v8_snapshot/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_snapshot.dir/build.make extern/v8/CMakeFiles/v8_snapshot.dir/build
.PHONY : v8_snapshot/fast

#=============================================================================
# Target rules for targets named v8_inspector

# Build rule for target.
v8_inspector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_inspector
.PHONY : v8_inspector

# fast build rule for target.
v8_inspector/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_inspector.dir/build.make extern/v8/CMakeFiles/v8_inspector.dir/build
.PHONY : v8_inspector/fast

#=============================================================================
# Target rules for targets named v8_libplatform

# Build rule for target.
v8_libplatform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_libplatform
.PHONY : v8_libplatform

# fast build rule for target.
v8_libplatform/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_libplatform.dir/build.make extern/v8/CMakeFiles/v8_libplatform.dir/build
.PHONY : v8_libplatform/fast

#=============================================================================
# Target rules for targets named v8_libsampler

# Build rule for target.
v8_libsampler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_libsampler
.PHONY : v8_libsampler

# fast build rule for target.
v8_libsampler/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_libsampler.dir/build.make extern/v8/CMakeFiles/v8_libsampler.dir/build
.PHONY : v8_libsampler/fast

#=============================================================================
# Target rules for targets named v8_libbase

# Build rule for target.
v8_libbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_libbase
.PHONY : v8_libbase

# fast build rule for target.
v8_libbase/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_libbase.dir/build.make extern/v8/CMakeFiles/v8_libbase.dir/build
.PHONY : v8_libbase/fast

#=============================================================================
# Target rules for targets named bytecode_builtins_list_generator

# Build rule for target.
bytecode_builtins_list_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bytecode_builtins_list_generator
.PHONY : bytecode_builtins_list_generator

# fast build rule for target.
bytecode_builtins_list_generator/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/bytecode_builtins_list_generator.dir/build.make extern/v8/CMakeFiles/bytecode_builtins_list_generator.dir/build
.PHONY : bytecode_builtins_list_generator/fast

#=============================================================================
# Target rules for targets named v8_torque_generated

# Build rule for target.
v8_torque_generated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8_torque_generated
.PHONY : v8_torque_generated

# fast build rule for target.
v8_torque_generated/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8_torque_generated.dir/build.make extern/v8/CMakeFiles/v8_torque_generated.dir/build
.PHONY : v8_torque_generated/fast

#=============================================================================
# Target rules for targets named torque

# Build rule for target.
torque: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 torque
.PHONY : torque

# fast build rule for target.
torque/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/torque.dir/build.make extern/v8/CMakeFiles/torque.dir/build
.PHONY : torque/fast

#=============================================================================
# Target rules for targets named mksnapshot

# Build rule for target.
mksnapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mksnapshot
.PHONY : mksnapshot

# fast build rule for target.
mksnapshot/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/mksnapshot.dir/build.make extern/v8/CMakeFiles/mksnapshot.dir/build
.PHONY : mksnapshot/fast

#=============================================================================
# Target rules for targets named v8-adler32

# Build rule for target.
v8-adler32: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8-adler32
.PHONY : v8-adler32

# fast build rule for target.
v8-adler32/fast:
	$(MAKE) $(MAKESILENT) -f extern/v8/CMakeFiles/v8-adler32.dir/build.make extern/v8/CMakeFiles/v8-adler32.dir/build
.PHONY : v8-adler32/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f extern/raylib/raylib/CMakeFiles/raylib.dir/build.make extern/raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f extern/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make extern/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f extern/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make extern/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named RmlCore

# Build rule for target.
RmlCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RmlCore
.PHONY : RmlCore

# fast build rule for target.
RmlCore/fast:
	$(MAKE) $(MAKESILENT) -f extern/RmlUi/CMakeFiles/RmlCore.dir/build.make extern/RmlUi/CMakeFiles/RmlCore.dir/build
.PHONY : RmlCore/fast

#=============================================================================
# Target rules for targets named RmlDebugger

# Build rule for target.
RmlDebugger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RmlDebugger
.PHONY : RmlDebugger

# fast build rule for target.
RmlDebugger/fast:
	$(MAKE) $(MAKESILENT) -f extern/RmlUi/CMakeFiles/RmlDebugger.dir/build.make extern/RmlUi/CMakeFiles/RmlDebugger.dir/build
.PHONY : RmlDebugger/fast

src/html/HTMLParser.o: src/html/HTMLParser.cpp.o
.PHONY : src/html/HTMLParser.o

# target to build an object file
src/html/HTMLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTMLParser.dir/build.make CMakeFiles/HTMLParser.dir/src/html/HTMLParser.cpp.o
.PHONY : src/html/HTMLParser.cpp.o

src/html/HTMLParser.i: src/html/HTMLParser.cpp.i
.PHONY : src/html/HTMLParser.i

# target to preprocess a source file
src/html/HTMLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTMLParser.dir/build.make CMakeFiles/HTMLParser.dir/src/html/HTMLParser.cpp.i
.PHONY : src/html/HTMLParser.cpp.i

src/html/HTMLParser.s: src/html/HTMLParser.cpp.s
.PHONY : src/html/HTMLParser.s

# target to generate assembly for a file
src/html/HTMLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTMLParser.dir/build.make CMakeFiles/HTMLParser.dir/src/html/HTMLParser.cpp.s
.PHONY : src/html/HTMLParser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... HTMLParser"
	@echo "... MyApp"
	@echo "... RmlCore"
	@echo "... RmlDebugger"
	@echo "... bytecode_builtins_list_generator"
	@echo "... d8"
	@echo "... glfw"
	@echo "... hello-world"
	@echo "... mksnapshot"
	@echo "... raylib"
	@echo "... shell"
	@echo "... torque"
	@echo "... v8-adler32"
	@echo "... v8-i18n-support"
	@echo "... v8_base_without_compiler"
	@echo "... v8_compiler"
	@echo "... v8_initializers"
	@echo "... v8_inspector"
	@echo "... v8_libbase"
	@echo "... v8_libplatform"
	@echo "... v8_libsampler"
	@echo "... v8_snapshot"
	@echo "... v8_torque_generated"
	@echo "... src/html/HTMLParser.o"
	@echo "... src/html/HTMLParser.i"
	@echo "... src/html/HTMLParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/koen/Documents/GitHub/BrowserC/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

